# Generated by Django 4.2.13 on 2024-05-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Vels', 'Vels'), ('Crescent', 'Crescent')], max_length=300),
        ),
    ]
