# Generated by Django 4.2.13 on 2024-05-30 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_program_student'),
        ('users', '0006_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.program'),
            preserve_default=False,
        ),
    ]
