# Generated by Django 4.2.13 on 2024-06-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.FileField(upload_to='path-to-upload'),
        ),
    ]
