# Generated by Django 4.2.13 on 2024-05-20 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='students',
            field=models.ManyToManyField(related_name='programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseitem',
            name='college',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='api.college'),
        ),
        migrations.AddField(
            model_name='courseitem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='college',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='api.college'),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.program'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
