# Generated by Django 4.2.13 on 2024-05-30 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='program',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.college'),
        ),
        migrations.AddField(
            model_name='chapteritem',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.chapter'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='college',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='api.college'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.subject'),
        ),
    ]
