# Generated by Django 4.2.13 on 2024-05-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_courseitem_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(choices=[('Vels', 'Vels_University'), ('Crescent', 'Crescent')], max_length=300),
        ),
    ]
