# Generated by Django 4.2.13 on 2024-06-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chapterquizanswerpercentage_chapterquiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterquiz',
            name='choice_d',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
