# Generated by Django 4.2.13 on 2024-05-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_college_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'permissions': [('view_specific_data', 'Can view specific data')]},
        ),
        migrations.RenameField(
            model_name='program',
            old_name='students',
            new_name='users',
        ),
    ]
