# Generated by Django 4.2.13 on 2024-06-10 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_subjectprogress_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapteritem',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='api.chapter'),
        ),
    ]
