# Generated by Django 4.2.13 on 2024-06-01 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_program'),
        ('api', '0004_chapterquiz_choice_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.chapter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.student')),
            ],
        ),
        migrations.DeleteModel(
            name='ChapterQuizAnswerPercentage',
        ),
    ]
