# Generated by Django 4.2.13 on 2024-05-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_program_options_rename_students_program_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='students',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='users',
            new_name='user',
        ),
    ]
