# Generated by Django 4.2.13 on 2024-06-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_subjectquiz_studentchapterquizanswer_chapterquiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentchapterquizprogresspercent',
            name='progress',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
