# Generated by Django 4.2.13 on 2024-05-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_college_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={},
        ),
    ]
