# Generated by Django 4.2.13 on 2024-05-21 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_teacher'),
        ('api', '0010_alter_college_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='user',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(related_name='courses', to='users.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='videos',
            field=models.FileField(upload_to='path-to-file'),
        ),
    ]
