# Generated by Django 4.2.13 on 2024-05-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_user_program_student_remove_course_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(choices=[('Vels University', 'Vels University'), ('Crescent', 'Crescent'), ('Jamal Mohamad', 'Jamal Mohamad'), ('Malla Reddy', 'Malla Reddy')], max_length=100),
        ),
    ]
