# Generated by Django 4.2.13 on 2024-05-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student_student_id'),
        ('api', '0012_alter_college_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChapterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('ppt', models.FileField(upload_to='path-to-upload')),
                ('video', models.FileField(upload_to='path-to-upload')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('college', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='api.college')),
            ],
        ),
        migrations.RemoveField(
            model_name='courseitem',
            name='college',
        ),
        migrations.RemoveField(
            model_name='courseitem',
            name='course',
        ),
        migrations.AlterField(
            model_name='program',
            name='student',
            field=models.ManyToManyField(related_name='programs', to='users.student'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseItem',
        ),
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.program'),
        ),
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(editable=False, related_name='Subjects', to='users.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.subject'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='college',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='api.college'),
        ),
    ]
