# Generated by Django 4.2.13 on 2024-05-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_chapter_chapteritem_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(default=1, upload_to='path-to-upload'),
            preserve_default=False,
        ),
    ]
