# Generated by Django 4.2.13 on 2024-05-23 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_subject_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
    ]
