# Generated by Django 4.2.13 on 2024-05-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_subject_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='student',
        ),
    ]
