# Generated by Django 4.2.13 on 2024-05-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_program_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='semester',
            field=models.IntegerField(default=1, verbose_name=range(1, 9)),
            preserve_default=False,
        ),
    ]
